package fr.golderpotato.ac.packet.packetlist;

import com.sun.xml.internal.bind.v2.runtime.reflect.Lister;
import fr.golderpotato.ac.packet.Packet;

/**
 * Created by Eliaz on 15/01/2017.
 * Credit to Faiden !!! =D
 */
public class PacketType {
    public static final PacketBuild ALL = new PacketBuild(666, "ALL", PacketSource.IN);
    public static final PacketBuild KEEP_ALIVE = new PacketBuild(0, "KeepAlive", PacketSource.IN);
    public static final PacketBuild LOGIN = new PacketBuild(1, "Login", PacketSource.IN);
    public static final PacketBuild CHAT = new PacketBuild(3, "Chat", PacketSource.IN);
    public static final PacketBuild UPDATE_TIME = new PacketBuild(4, "UpdateTime", PacketSource.OUT);
    public static final PacketBuild ENTITY_EQUIPMENT = new PacketBuild(5, "EntityEquipment", PacketSource.OUT);
    public static final PacketBuild SPAWN_POSITION = new PacketBuild(6, "SpawnPosition", PacketSource.OUT);
    public static final PacketBuild UPDATE_HEALTH = new PacketBuild(8, "UpdateHealth", PacketSource.OUT);
    public static final PacketBuild RESPAWN = new PacketBuild(9, "Respawn", PacketSource.OUT);
    public static final PacketBuild HELD_ITEM_SLOT = new PacketBuild(16, "HeldItemSlot", PacketSource.IN);
    public static final PacketBuild USE_ENTITY = new PacketBuild(7, "UseEntity", PacketSource.IN);
    public static final PacketBuild FLYING = new PacketBuild(10, "Flying", PacketSource.IN);
    public static final PacketBuild POSITION = new PacketBuild(13, "Position", PacketSource.IN);
    public static final PacketBuild LOOK = new PacketBuild(12, "Look", PacketSource.IN);
    public static final PacketBuild POSITION_LOOK = new PacketBuild(13, "PositionLook", PacketSource.IN);
    public static final PacketBuild BLOCK_DIG = new PacketBuild(14, "BlockDig", PacketSource.IN);
    public static final PacketBuild BLOCK_PLACE = new PacketBuild(15, "BlockPlace", PacketSource.IN);
    public static final PacketBuild ARM_ANIMATION = new PacketBuild(18, "ArmAnimation", PacketSource.IN);
    public static final PacketBuild ENTITY_ACTION = new PacketBuild(19, "EntityAction", PacketSource.IN);
    public static final PacketBuild STEER_VEHICLE = new PacketBuild(27, "SteerVehicle", PacketSource.IN);
    public static final PacketBuild WINDOW_CLICK = new PacketBuild(102, "WindowClick", PacketSource.IN);
    public static final PacketBuild SET_CREATIVE_SLOT = new PacketBuild(107, "SetCreativeSlot", PacketSource.IN);
    public static final PacketBuild ENCHANT_ITEM = new PacketBuild(108, "EnchantItem", PacketSource.IN);
    public static final PacketBuild SETTINGS = new PacketBuild(204, "Settings", PacketSource.IN);
    public static final PacketBuild CLIENT_COMMAND = new PacketBuild(205, "ClientCommand", PacketSource.IN);
    public static final PacketBuild SPECTATE = new PacketBuild(-1, "Spectate", PacketSource.IN);
    public static final PacketBuild RESOURCE_PACK_STATUS = new PacketBuild(-1, "ResourcePackStatus", PacketSource.IN);
    public static final PacketBuild BED = new PacketBuild(17, "Bed", PacketSource.OUT);
    public static final PacketBuild ANIMATION = new PacketBuild(18, "Animation", PacketSource.OUT);
    public static final PacketBuild NAMED_ENTITY_SPAWN = new PacketBuild(20, "NamedEntitySpawn", PacketSource.OUT);
    public static final PacketBuild COLLECT = new PacketBuild(22, "Collect", PacketSource.OUT);
    public static final PacketBuild SPAWN_ENTITY = new PacketBuild(23, "SpawnEntity", PacketSource.OUT);
    public static final PacketBuild SPAWN_ENTITY_LIVING = new PacketBuild(24, "SpawnEntityLiving", PacketSource.OUT);
    public static final PacketBuild SPAWN_ENTITY_PAINTING = new PacketBuild(25, "SpawnEntityPainting", PacketSource.OUT);
    public static final PacketBuild SPAWN_ENTITY_EXPERIENCE_ORB = new PacketBuild(26, "SpawnEntityExperienceOrb", PacketSource.OUT);
    public static final PacketBuild ENTITY_VELOCITY = new PacketBuild(28, "EntityVelocity", PacketSource.OUT);
    public static final PacketBuild ENTITY_DESTROY = new PacketBuild(29, "EntityDestroy", PacketSource.OUT);
    public static final PacketBuild ENTITY = new PacketBuild(30, "Entity", PacketSource.OUT);
    public static final PacketBuild REL_ENTITY_MOVE = new PacketBuild(31, "RelEntityMove", PacketSource.OUT);
    public static final PacketBuild ENTITY_LOOK = new PacketBuild(32, "EntityLook", PacketSource.OUT);
    public static final PacketBuild ENTITY_MOVE_LOOK = new PacketBuild(33, "RelEntityMoveLook", PacketSource.OUT);
    public static final PacketBuild ENTITY_TELEPORT = new PacketBuild(34, "EntityTeleport", PacketSource.OUT);
    public static final PacketBuild ENTITY_HEAD_ROTATION = new PacketBuild(35, "EntityHeadRotation", PacketSource.OUT);
    public static final PacketBuild ENTITY_STATUS = new PacketBuild(38, "EntityStatus", PacketSource.OUT);
    public static final PacketBuild ATTACH_ENTITY = new PacketBuild(39, "AttachEntity", PacketSource.OUT);
    public static final PacketBuild ENTITY_METADATA = new PacketBuild(40, "EntityMetadata", PacketSource.OUT);
    public static final PacketBuild ENTITY_EFFECT = new PacketBuild(41, "EntityEffect", PacketSource.OUT);
    public static final PacketBuild REMOVE_ENTITY_EFFECT = new PacketBuild(42, "RemoveEntityEffect", PacketSource.OUT);
    public static final PacketBuild EXPERIENCE = new PacketBuild(43, "Experience", PacketSource.OUT);
    public static final PacketBuild UPDATE_ATTRIBUTES = new PacketBuild(44, "UpdateAttributes", PacketSource.OUT);
    public static final PacketBuild MAP_CHUNK = new PacketBuild(51, "MapChunk", PacketSource.OUT);
    public static final PacketBuild MULTI_BLOCK_CHANGE = new PacketBuild(52, "MultiBlockChange", PacketSource.OUT);
    public static final PacketBuild BLOCK_CHANGE = new PacketBuild(53, "BlockChange", PacketSource.OUT);
    public static final PacketBuild BLOCK_ACTION = new PacketBuild(54, "BlockAction", PacketSource.OUT);
    public static final PacketBuild BLOCK_BREAK_ANIMATION = new PacketBuild(55, "BlockBreakAnimation", PacketSource.OUT);
    public static final PacketBuild MAP_CHUNK_BULK = new PacketBuild(56, "MapChunkBulk", PacketSource.OUT);
    public static final PacketBuild EXPLOSION = new PacketBuild(60, "Explosion", PacketSource.OUT);
    public static final PacketBuild WORLD_EVENT = new PacketBuild(61, "WorldEvent", PacketSource.OUT);
    public static final PacketBuild NAMED_SOUND_EFFECT = new PacketBuild(62, "NamedSoundEffect", PacketSource.OUT);
    public static final PacketBuild WORLD_PARTICLES = new PacketBuild(63, "WorldParticles", PacketSource.OUT);
    public static final PacketBuild GAME_STATE_CHANGE = new PacketBuild(70, "GameStateChange", PacketSource.OUT);
    public static final PacketBuild SPAWN_ENTITY_WEATHER = new PacketBuild(71, "SpawnEntityWeather", PacketSource.OUT);
    public static final PacketBuild OPEN_WINDOW = new PacketBuild(100, "OpenWindow", PacketSource.OUT);
    public static final PacketBuild CLOSE_WINDOW = new PacketBuild(101, "CloseWindow", PacketSource.IN);
    public static final PacketBuild SET_SLOT = new PacketBuild(103, "SetSlot", PacketSource.OUT);
    public static final PacketBuild WINDOW_ITEMS = new PacketBuild(104, "WindowItems", PacketSource.OUT);
    public static final PacketBuild CRAFT_PROGRESS_BAR = new PacketBuild(105, "WindowData", PacketSource.OUT);
    public static final PacketBuild TRANSACTION = new PacketBuild(106, "Transaction", PacketSource.IN);
    public static final PacketBuild UPDATE_SIGN = new PacketBuild(130, "UpdateSign", PacketSource.IN);
    public static final PacketBuild MAP = new PacketBuild(131, "Map", PacketSource.OUT);
    public static final PacketBuild TILE_ENTITY_DATA = new PacketBuild(132, "TileEntityData", PacketSource.OUT);
    public static final PacketBuild OPEN_SIGN_ENTITY = new PacketBuild(133, "OpenSignEditor", PacketSource.OUT);
    public static final PacketBuild STATISTICS = new PacketBuild(200, "Statistic", PacketSource.OUT);
    public static final PacketBuild PLAYER_INFO = new PacketBuild(201, "PlayerInfo", PacketSource.OUT);
    public static final PacketBuild ABILITIES = new PacketBuild(202, "Abilities", PacketSource.IN);
    public static final PacketBuild TAB_COMPLETE = new PacketBuild(203, "TabComplete", PacketSource.IN);
    public static final PacketBuild SCOREBOARD_OBJECTIVE = new PacketBuild(206, "ScoreboardObjective", PacketSource.OUT);
    public static final PacketBuild SCOREBOARD_SCORE = new PacketBuild(207, "ScoreboardScore", PacketSource.OUT);
    public static final PacketBuild SCOREBOARD_DISPLAY_OBJECTIVE = new PacketBuild(208, "ScoreboardDisplayObjective", PacketSource.OUT);
    public static final PacketBuild SCOREBOARD_TEAM = new PacketBuild(209, "ScoreboardTeam", PacketSource.OUT);
    public static final PacketBuild CUSTOM_PAYLOAD = new PacketBuild(250, "CustomPayload", PacketSource.IN);
    public static final PacketBuild KICK_DISCONNECT = new PacketBuild(255, "KickDisconnect", PacketSource.OUT);
    public static final PacketBuild SERVER_DIFFICULTY = new PacketBuild(-1, "ServerDifficulty", PacketSource.OUT);
    public static final PacketBuild COMBAT_EVENT = new PacketBuild(-1, "CombatEvent", PacketSource.OUT);
    public static final PacketBuild CAMERA = new PacketBuild(-1, "Camera", PacketSource.OUT);
    public static final PacketBuild WORLD_BORDER = new PacketBuild(-1, "WorldBorder", PacketSource.OUT);
    public static final PacketBuild TITLE = new PacketBuild(-1, "Title", PacketSource.OUT);
    public static final PacketBuild SET_COMPRESSION = new PacketBuild(-1, "SetCompression", PacketSource.OUT);
    public static final PacketBuild PLAYER_LIST_HEADER_FOOTER = new PacketBuild(-1, "PlayerListHeaderFooter", PacketSource.OUT);
    public static final PacketBuild RESOURCE_PACK_SEND = new PacketBuild(-1, "ResourcePackSend", PacketSource.OUT);
    public static final PacketBuild UPDATE_ENTITY_NBT = new PacketBuild(-1, "UpdateEntityNBT", PacketSource.OUT);
}
